name: mikkopelttari
favicon: null
layout_spectrum: 0.52415
typography_spectrum: 0.81653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1f1f'
    - '#5b5b5b'
    - '#6a6a6a'
    - '#7f7f7f'
    - '#a8a8a8'
  brandStrength: 1
  lightness: 0.966783398296684
  saturation: 0.22738416329957545
  rhythmicContrast: 0.7690006042830646
purpose: []
